apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: address-app-v2
  labels:
    app: address-app
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: address-app
      version: v2
  template:
    metadata:
      labels:
        app: address-app
        version: v2
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
    spec:
      containers:
        - name: address-app
          image: fabiosalasm/address-app:v2.0.0
          imagePullPolicy: Never # Use local repository
          env:
            - name: "SERVER_PORT"
              value: "8081"
            - name: "MANAGEMENT_ENDPOINT_HEALTH_PROBES_ENABLED"
              value: "on"
          ports:
            - name: server-port
              containerPort: 8081
          resources:
            requests:
              cpu: 200m
              memory: 180Mi
            limits:
              cpu: 300m
              memory: 300Mi
          livenessProbe:
            initialDelaySeconds: 20
            periodSeconds: 15
            timeoutSeconds: 3
            httpGet:
              port: server-port
              path: /actuator/health/liveness
              httpHeaders:
                - name: Host
                  value: KubernetesReadinessProbe
          readinessProbe:
            initialDelaySeconds: 20
            periodSeconds: 15
            timeoutSeconds: 3
            httpGet:
              port: server-port
              path: /actuator/health/readiness
              httpHeaders:
                - name: Host
                  value: KubernetesReadinessProbe
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: job-app-v2
  labels:
    app: job-app
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: job-app
      version: v2
  template:
    metadata:
      labels:
        app: job-app
        version: v2
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
    spec:
      containers:
        - name: job-app
          image: fabiosalasm/job-app:v2.0.0
          imagePullPolicy: Never # Use local repository
          env:
            - name: "SERVER_PORT"
              value: "8082"
            - name: "MANAGEMENT_ENDPOINT_HEALTH_PROBES_ENABLED"
              value: "on"
          ports:
            - name: server-port
              containerPort: 8082
          resources:
            requests:
              cpu: 200m
              memory: 180Mi
            limits:
              cpu: 300m
              memory: 300Mi
          livenessProbe:
            initialDelaySeconds: 20
            periodSeconds: 15
            timeoutSeconds: 3
            httpGet:
              port: server-port
              path: /actuator/health/liveness
              httpHeaders:
                - name: Host
                  value: KubernetesReadinessProbe
          readinessProbe:
            initialDelaySeconds: 20
            periodSeconds: 15
            timeoutSeconds: 3
            httpGet:
              port: server-port
              path: /actuator/health/readiness
              httpHeaders:
                - name: Host
                  value: KubernetesReadinessProbe
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: company-app-v2
  labels:
    app: company-app
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: company-app
      version: v2
  template:
    metadata:
      labels:
        app: company-app
        version: v2
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
    spec:
      containers:
        - name: company-app
          image: fabiosalasm/company-app:v2.0.0
          imagePullPolicy: Never # Use local repository
          env:
            - name: "SERVER_PORT"
              value: "8080"
            - name: "MANAGEMENT_ENDPOINT_HEALTH_PROBES_ENABLED"
              value: "on"
            - name: "APP_ADDRESSAPPURL"
              value: "http://address-app.default.svc.cluster.local:8081"
            - name: "APP_JOBAPPURL"
              value: "http://job-app.default.svc.cluster.local:8082"
          ports:
            - name: server-port
              containerPort: 8080
          resources:
            requests:
              cpu: 200m
              memory: 180Mi
            limits:
              cpu: 300m
              memory: 300Mi
          livenessProbe:
            initialDelaySeconds: 20
            periodSeconds: 15
            timeoutSeconds: 3
            httpGet:
              port: server-port
              path: /actuator/health/liveness
              httpHeaders:
                - name: Host
                  value: KubernetesReadinessProbe
          readinessProbe:
            initialDelaySeconds: 20
            periodSeconds: 15
            timeoutSeconds: 3
            httpGet:
              port: server-port
              path: /actuator/health/readiness
              httpHeaders:
                - name: Host
                  value: KubernetesReadinessProbe