apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: company-app
  namespace: default
spec:
  virtualHost:
    domains:
      - '*'
    routes:
      - matchers:
          - prefix: /
        routeAction:
          single:
            upstream:
              name: default-company-app-8080
              namespace: default