apiVersion: skaffold/v2beta7
kind: Config
metadata:
  name: address-app
build:
  tagPolicy:
    gitCommit: {} # https://skaffold.dev/docs/pipeline-stages/taggers/
  artifacts:
  - image: fabiosalasm/address-app
  local: {}
deploy:
  kubectl:
    manifests:
    - ../kubernetes/address-app/deployment.yaml
    - ../kubernetes/address-app/service.yaml
