apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
networking:
  apiServerAddress: "127.0.0.1"
  apiServerPort: 6443
  podSubnet: "10.240.0.0/16"
  serviceSubnet: "10.0.0.0/16"
  disableDefaultCNI: true
nodes:
  - role: control-plane
    image: kindest/node:v1.16.15@sha256:a89c771f7de234e6547d43695c7ab047809ffc71a0c3b65aa54eda051c45ed20
    extraPortMappings: # Integration with Gloo
      - containerPort: 31500
        hostPort: 31500
        listenAddress: "127.0.0.1"
        protocol: TCP
      - containerPort: 32500
        hostPort: 32500
        listenAddress: "127.0.0.1"
        protocol: TCP