server:
  servlet:
    jsp:
      registered: off
  port: 8080
app:
  address-app-url: "http://localhost:8081"
  job-app-url: "http://localhost:8082"
spring:
  application:
    name: "company-app"
  sleuth:
    enabled: on