apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  namespace: demo
  name: company-app-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  namespace: demo
  name: company-app-vs
spec:
  hosts:
    - "*"
  gateways:
    - company-app-gateway
  http:
    - name: "company-app-default-route"
      route:
        - destination:
            host: "company-app.demo.svc.cluster.local"
            port:
              number: 8080
            subset: v1
          weight: 90
          headers:
            response:
              set:
                version: v1
        - destination:
            host: "company-app.demo.svc.cluster.local"
            port:
              number: 8080
            subset: v2
          weight: 10
          headers:
            response:
              set:
                version: v2
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  namespace: demo
  name: company-app-dr
spec:
  host: "company-app.demo.svc.cluster.local"
  subsets:
    - name: v1
      labels:
        version: v1
    - name: v2
      labels:
        version: v2