apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: job-app-v1
  labels:
    app: job-app
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: job-app
      version: v1
  template:
    metadata:
      labels:
        app: job-app
        version: v1
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
    spec:
      containers:
        - name: job-app
          image: docker.io/fabiosalasm/job-app:v1.0.0
          imagePullPolicy: IfNotPresent
          env:
            - name: "SERVER_PORT"
              value: "8082"
            - name: "MANAGEMENT_ENDPOINT_HEALTH_PROBES_ENABLED"
              value: "on"
          ports:
            - name: server-port
              containerPort: 8082
          resources:
            requests:
              cpu: 300m
              memory: 300Mi
            limits:
              memory: 300Mi
          livenessProbe:
            initialDelaySeconds: 30
            periodSeconds: 15
            timeoutSeconds: 3
            httpGet:
              port: server-port
              path: /actuator/health/liveness
              httpHeaders:
                - name: Host
                  value: KubernetesReadinessProbe
          readinessProbe:
            initialDelaySeconds: 30
            periodSeconds: 15
            timeoutSeconds: 3
            httpGet:
              port: server-port
              path: /actuator/health/readiness
              httpHeaders:
                - name: Host
                  value: KubernetesReadinessProbe