apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: company-app-v1
  labels:
    app: company-app
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: company-app
      version: v1
  template:
    metadata:
      labels:
        app: company-app
        version: v1
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
    spec:
      containers:
        - name: company-app
          image: docker.io/fabiosalasm/company-app:v1.0.0
          imagePullPolicy: IfNotPresent
          env:
            - name: "SERVER_PORT"
              value: "8080"
            - name: "MANAGEMENT_ENDPOINT_HEALTH_PROBES_ENABLED"
              value: "on"
            - name: "APP_ADDRESSAPPURL"
              value: "http://address-app.default.svc.cluster.local:8081"
            - name: "APP_JOBAPPURL"
              value: "http://job-app.default.svc.cluster.local:8082"
          ports:
            - name: server-port
              containerPort: 8080
          resources:
            requests:
              cpu: 300m
              memory: 300Mi
            limits:
              memory: 300Mi
          livenessProbe:
            initialDelaySeconds: 30
            periodSeconds: 15
            timeoutSeconds: 3
            httpGet:
              port: server-port
              path: /actuator/health/liveness
              httpHeaders:
                - name: Host
                  value: KubernetesReadinessProbe
          readinessProbe:
            initialDelaySeconds: 30
            periodSeconds: 15
            timeoutSeconds: 3
            httpGet:
              port: server-port
              path: /actuator/health/readiness
              httpHeaders:
                - name: Host
                  value: KubernetesReadinessProbe