apiVersion: skaffold/v2beta7
kind: Config
metadata:
  name: job-app
build:
  tagPolicy:
    gitCommit: {} # https://skaffold.dev/docs/pipeline-stages/taggers/
  artifacts:
    - image: fabiosalasm/job-app
  local: {}
deploy:
  kubectl:
    manifests:
      - ../kubernetes/job-app/deployment.yaml
      - ../kubernetes/job-app/service.yaml